run:
	bochs -f bochsrc -q

debug:
	bochs -f bochsgdb -q

runSerial:
	bochs -f bochsrc_serial -q

debugSerial:
	bochs -f bochsgdb_serial -q

runTerm:
	bochs -f bochsrc_term -q

debugTerm:
	bochs -f bochsgdb_term -q

clean:
	rm -f disk.img
	rm -f bochsout.txt
	rm -f snapshot.txt

